// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqKhXFBv-QlCJwVsBCjn9Iwn6ouyPJ0r4',
    appId: '1:1008329866369:web:a629266ff53b9595d76180',
    messagingSenderId: '1008329866369',
    projectId: 'chatapplication-b2437',
    authDomain: 'chatapplication-b2437.firebaseapp.com',
    databaseURL: 'https://chatapplication-b2437-default-rtdb.firebaseio.com',
    storageBucket: 'chatapplication-b2437.appspot.com',
    measurementId: 'G-GP3MDT9R0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMLPPVTt7c9Buvne3h6I-_oh1MfZZ2Rc',
    appId: '1:1008329866369:android:36c6e30a8be3f9e9d76180',
    messagingSenderId: '1008329866369',
    projectId: 'chatapplication-b2437',
    databaseURL: 'https://chatapplication-b2437-default-rtdb.firebaseio.com',
    storageBucket: 'chatapplication-b2437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGEMUs53stY2ujcqQ1t3UMKAHNLl3MkVg',
    appId: '1:1008329866369:ios:00e10e2deb7e27afd76180',
    messagingSenderId: '1008329866369',
    projectId: 'chatapplication-b2437',
    databaseURL: 'https://chatapplication-b2437-default-rtdb.firebaseio.com',
    storageBucket: 'chatapplication-b2437.appspot.com',
    iosClientId: '1008329866369-knqhkli1vjkg6gumisq32ip1noosegrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGEMUs53stY2ujcqQ1t3UMKAHNLl3MkVg',
    appId: '1:1008329866369:ios:e4b4f109bee638f7d76180',
    messagingSenderId: '1008329866369',
    projectId: 'chatapplication-b2437',
    databaseURL: 'https://chatapplication-b2437-default-rtdb.firebaseio.com',
    storageBucket: 'chatapplication-b2437.appspot.com',
    iosClientId: '1008329866369-jdet5k9ipoo428dojv5rqa7h1jgeg0ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppFlutter.RunnerTests',
  );
}
